### ISSUE TITLE
YAML Bib Help

### ISSUE THREAD

**Issue by shanmiss6** [anyone-can-cook/rclass2#18]
Hey, the two files that were given as support for bibliography are still a bit confusing. I am trying to do bibliography: reference.bib in the header and an error returns. DO i specify the file path here or? Can anyone point me to a syntax example? @ozanj  @briannawright135

**Comment by ozanj** [comment]
Hey @shanmiss6 !

can you repost this question on the `rclass2_w22_student_issues` page rather than the `rclass2` page? here is the link:

https://github.com/anyone-can-cook/rclass2_w22_student_issues/issues 

as to your question, you specify the filepath of the .bib file and the .csl file within the YAML header at top of .rmd file like this

`---
title: 'Analysis Report'
output: pdf_document
bibliography: <insert filepath to references.bib>
csl: <insert filepath to apa.csl>
---`

let me know if this works and I'll reply in the `rclass2_w22_student_issues`  page
